In [65]:
import timeit

import torch

In [3]:
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.rand(2, 3)

tensor([[0.1047, 0.7357, 0.6401],
        [0.5966, 0.2454, 0.4312]])

In [55]:
data = torch.randn(2, 3)
print(data, data.mean(), data.std())

tensor([[-0.3236, -0.4463,  0.4950],
        [ 0.0680,  2.2976,  2.1119]]) tensor(0.7004) tensor(1.2123)


In [56]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [58]:
torch.rand(2, 3).cuda()

AssertionError: Torch not compiled with CUDA enabled

In [59]:
torch.rand(2, 3) + torch.rand(2, 3, dtype=torch.double)

tensor([[1.2653, 0.6201, 1.2306],
        [0.9800, 0.5115, 1.1510]], dtype=torch.float64)

In [60]:
torch.tensor([1, 2, 3]).dot(torch.tensor([1, 2, 3]))

tensor(14)

In [62]:
torch.tensor([0, 1]).exp()

tensor([1.0000, 2.7183])

In [109]:
M = torch.rand(10000, 10000)
print(M.mm(M).mm(M).device)
timeit.timeit(lambda: M.mm(M).mm(M), number=2)

cpu


7.998650291992817

In [111]:
N = torch.rand(10000, 10000, device="mps")
print(N.mm(N).mm(N).device)
timeit.timeit(lambda: N.mm(N).mm(N), number=2)

mps:0


0.0011211669771000743

In [71]:
torch.backends.mps.is_available()

True

In [114]:
x = torch.tensor([2.0], requires_grad=True)
y = torch.tensor([3.0], requires_grad=True)
z = (x + y) * (y - 2)
print(z)
z.backward()
print(x.grad, y.grad)

tensor([5.], grad_fn=<MulBackward0>)
tensor([1.]) tensor([6.])


In [ ]:
x = torch.tensor([4.0], requires_grad=True)
y = x**2
print(y)
y.backward()
print(x.grad)

tensor([16.], grad_fn=<PowBackward0>)
tensor([8.])


In [ ]:
M = torch.arange(6).view(2, 3)

print(M)
print(M.storage())
print(M.stride())
print(M.is_contiguous())

N = M.t()

print(N)
print(N.storage())
print(N.stride())
print(N.is_contiguous())

tensor([[0, 1, 2],
        [3, 4, 5]])
 0
 1
 2
 3
 4
 5
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
(3, 1)
True
tensor([[0, 3],
        [1, 4],
        [2, 5]])
 0
 1
 2
 3
 4
 5
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]
(1, 3)
False


In [136]:
x = torch.arange(12).view(3, 4)
print(x)
x[:, 2:4]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])